[package]
name = "spectre-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
console = "0.15"
serde_json = "1"
toml = "0.8"

spectre = { path = "../spectre-lib", features = ["cli"] }