[package]
name = "spectre-gui"
version = "0.1.0"
edition = "2021"

[lib]
name = "spectre_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

spectre = { path = "../../crates/core" }

